# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Windows Rules https://wiki.hyprland.org/0.45.0/Configuring/Window-Rules/ #

# float on Necessary Windows
windowrule = match:class ^(org.pulseaudio.pavucontrol), float on
windowrule = match:class ^(com.saivert.pwvucontrol), float on
windowrule = match:class ^(Sforzando), float on
windowrule = match:class ^()$, match:title ^(Picture in picture)$, float on
windowrule = match:class ^()$,match:title ^(Save File)$, float on
windowrule = match:class ^()$,match:title ^(Open File)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$, float on
windowrule = match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$, float on
windowrule = match:class ^(CachyOSHello)$, float on
windowrule = match:class ^(zenity)$, float on

# General window rules
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, size 960 540 
windowrule = match:title ^(Picture-in-Picture)$, move 25%-
windowrule = match:title ^(imv|mpv|danmufloat on|termfloat|nemo|ncmpcpp)$, float on
windowrule = match:title ^(imv|mpv|danmufloat on|termfloat|nemo|ncmpcpp)$, move 25%-
windowrule = match:title ^(imv|mpv|danmufloat on|termfloat|nemo|ncmpcpp)$, size 960 540 
windowrule = match:title ^(danmufloat on)$, pin on
windowrule = match:title ^(danmufloat on|termfloat)$, rounding 5 
windowrule = match:class ^(kitty|Alacritty)$, animation slide right 
windowrule = match:class ^(org.mozilla.firefox)$, no_blur on

windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = match:class ^(xwaylandvideobridge)$, no_anim on
windowrule = match:class ^(xwaylandvideobridge)$, no_initial_focus on 
windowrule = match:class ^(xwaylandvideobridge)$, max_size 1 1 
windowrule = match:class ^(xwaylandvideobridge)$, no_blur on
windowrule = match:class ^(xwaylandvideobridge)$, no_focus on

windowrule = match:class Godot, match:title Godot , tile on
windowrule = match:title .*\(DEBUG\), float on 

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize 

# Fix some dragging issues with XWayland
# windowrule = match:class ^$, match:title ^$, match:xwayland 1, float oning:1, fullscreen:0, pinned:0, nofocusm

windowrule = match:class (clipse), float on 
windowrule = match:class (clipse), size 622 652 
windowrule = match:class (clipse), stay_focused on

# Windows Rules End #

# Workspaces Rules https://wiki.hyprland.org/0.45.0/Configuring/Workspace-Rules/ #
# workspace = 1, default:true, monitor:$priMon
# workspace = 6, default:true, monitor:$secMon
# Workspace selectors https://wiki.hyprland.org/0.45.0/Configuring/Workspace-Rules/#workspace-selectors
# workspace = r[1-5], monitor:$priMon
# workspace = r[6-10], monitor:$secMon
# workspace = special:scratchpad, on-created-empty:$applauncher
# no_gaps_when_only deprecated instead workspaces rules with selectors can do the same
# Smart gaps from 0.45.0 https://wiki.hyprland.org/0.45.0/Configuring/Workspace-Rules/#smart-gaps
# Workspaces Rules End #

# Layers Rules #
layerrule = match:namespace logout_dialog, animation slide top
# layerrule = animation popin 50%, waybar
layerrule = match:namespace waybar, animation slide down
layerrule = match:namespace wallpaper, animation fade 50%
# Layers Rules End #


