alias sudo="sudo "
alias godot="/usr/bin/godot"
alias okularkirigami="kate"
alias vim="nvim"
alias vvim="nvim ."
alias gdvim="gdvim.sh"
alias swap-to-windows="swap-to-windows.sh"
alias update-grub="grub-mkconfig -o /boot/grub/grub.cfg"
